const PUSH_REGISTERED = "PUSH_REGISTERED"
const PUSH_NOTIFICATION = "PUSH_NOTIFICATION"
const SAVE_NOTIFICATION = "SAVE_NOTIFICATION"
const VIEW_NOTIFICATION = "VIEW_NOTIFICATION"
const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS"

export default {
  PUSH_REGISTERED,
  PUSH_NOTIFICATION,
  SAVE_NOTIFICATION,
  VIEW_NOTIFICATION,
  DELETE_NOTIFICATIONS,
}
